import turtle

def drawA(t):
    t.forward(15)
    t.left(180)
    t.forward(30)
    t.right(-45)
    t.forward(30)
    t.backward(50)
    t.penup()
    t.home()
    t.forward(15)
    t.right(45)
    t.pendown()
    t.forward(30)
    t.backward(50)
    t.penup()
    t.home()
    
def drawB(t):
    t.circle(20, 180)
    t.left(90)
    t.forward(40)
    t.right(90)
    t.circle(20, -180)
    t.left(90)
    t.forward(40)
    t.penup()
    t.home()

def drawC(t):
    t.circle(20, -180)
    t.penup()
    t.home()
    
def drawD(t):
    t.circle(20, 180)
    t.home()
    
def drawE(t):
    t.left(90)
    t.forward(90)
    t.right(90)
    t.forward(30)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.forward(45)
    t.left(90)
    t.forward(30)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.forward(45)
    t.left(90)
    t.forward(30)
    t.penup()
    t.home()

def drawF(t):
    t.left(90)
    t.forward(90)
    t.right(90)
    t.forward(30)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.forward(45)
    t.left(90)
    t.forward(30)
    t.left(180)
    t.forward(30)
    t.left(90)
    t.penup()
    t.home()
    
def drawG(t):
    t.circle(40, -180)
    t.penup()
    t.home()
    t.left(90)
    t.pendown()
    t.forward(20)
    t.left(90)
    t.forward(15)
    
def drawH(t):
    t.forward(30)
    t.left(90)
    t.forward(45)
    t.left(180)
    t.forward(90)
    t.penup()
    t.home()
    t.left(180)
    t.pendown()
    t.forward(30)
    t.left(90)
    t.forward(45)
    t.left(180)
    t.forward(90)
    t.penup()
    t.home()
    
def drawI(t):
    t.forward(20)
    t.left(180)
    t.forward(40)
    t.penup()
    t.home()
    t.left(90)
    t.pendown()
    t.forward(30)
    t.right(90)
    t.forward(20)
    t.left(180)
    t.forward(40)
    t.penup()
    t.right(90)
    t.home()
    
def drawJ(t):
    t.right(90)
    t.penup()
    t.forward(20)
    t.pendown()
    t.circle(10, 180)
    t.penup()
    t.pendown()
    t.forward(20)
    t.left(90)
    t.forward(20)
    
def drawK(t):
    t.left(90)
    t.forward(20)
    t.backward(40)
    t.home()
    t.right(45)
    t.forward(30)
    t.home()
    t.left(45)
    t.forward(30)
    t.home()
    
def drawL(t):
    t.left(180)
    t.forward(30)
    t.right(90)
    t.forward(90)
    t.penup()
    t.home()

def drawM(t):
    t.penup()
    t.left(90)
    t.forward(90)
    t.left(90)
    t.forward(45)
    t.pendown()
    t.home()
    t.penup()
    t.left(90)
    t.forward(90)
    t.right(90)
    t.forward(45)
    t.pendown()
    t.home()
    t.penup()
    t.forward(45)
    t.left(90)
    t.pendown()
    t.forward(90)
    t.backward(160)
    t.penup()
    t.home()
    t.backward(45)
    t.left(90)
    t.pendown()
    t.forward(90)
    t.backward(160)
    t.penup()
    t.home()
    
def drawN(t):
    t.left(90)
    t.forward(40)
    t.right(130)
    t.forward(60)
    t.left(130)
    t.forward(45)
    
def drawO(t):
    t.circle(30)
    
def drawP(t):
    t.circle(20, 180)
    t.home()
    t.right(90)
    t.forward(20)
    t.penup()
    t.home()
    
def drawQ(t):
    t.circle(30)
    t.right(45)
    t.forward(20)
    t.penup()
    t.home()
    
def drawR(t):
    t.circle(20, 180)
    t.home()
    t.right(90)
    t.forward(20)
    t.penup()
    t.home()
    t.pendown()
    t.right(45)
    t.forward(30)
    t.penup()
    t.home()
def drawS(t):
    t.circle(20, -180)
    t.penup()
    t.home()
    t.pendown()
    t.left(180)
    t.circle(20, -180)
    
def drawT(t):
    t.left(90)
    t.forward(90)
    t.right(90)
    t.forward(45)
    t.left(180)
    t.forward(90)
    t.penup()
    t.left(180)
    t.home()

def drawU(t):
    t.right(90)
    t.forward(30)
    t.circle(25, 180)
    t.forward(30)
    t.penup()
    t.home()
    
def drawV(t):
    t.penup()
    t.left(90)
    t.forward(90)
    t.left(90)
    t.forward(45)
    t.pendown()
    t.home()
    t.penup()
    t.left(90)
    t.forward(90)
    t.right(90)
    t.forward(45)
    t.pendown()
    t.home()
    
def drawW(t):
    t.penup()
    t.left(-90)
    t.forward(90)
    t.left(-90)
    t.forward(45)
    t.pendown()
    t.home()
    t.penup()
    t.left(-90)
    t.forward(90)
    t.right(-90)
    t.forward(45)
    t.pendown()
    t.home()
    t.penup()
    t.forward(45)
    t.left(-90)
    t.pendown()
    t.forward(90)
    t.backward(160)
    t.penup()
    t.home()
    t.backward(45)
    t.left(-90)
    t.pendown()
    t.forward(90)
    t.backward(160)
    t.penup()
    t.home()
    
def drawX(t):
    t.penup()
    t.left(90)
    t.forward(90)
    t.left(90)
    t.forward(45)
    t.pendown()
    t.home()
    t.penup()
    t.left(90)
    t.forward(90)
    t.right(90)
    t.forward(45)
    t.pendown()
    t.home()
    t.penup()
    t.right(90)
    t.forward(90)
    t.right(90)
    t.forward(45)
    t.pendown()
    t.home()
    t.penup()
    t.right(90)
    t.forward(90)
    t.left(90)
    t.forward(45)
    t.pendown()
    t.home()
    
def drawY(t):
    t.penup()
    t.left(90)
    t.forward(90)
    t.left(90)
    t.forward(45)
    t.pendown()
    t.home()
    t.penup()
    t.left(90)
    t.forward(90)
    t.right(90)
    t.forward(45)
    t.pendown()
    t.home()
    t.penup()
    t.right(90)
    t.forward(90)
    t.forward(45)
    t.pendown()
    t.home()
    
def drawZ(t):
    t.forward(30)
    t.penup()
    t.left(180)
    t.forward(30)
    t.right(90)
    t.forward(30)
    t.right(90)
    t.pendown()
    t.forward(30)
    t.home()

if __name__ == '__main__':
    t = turtle.Turtle()
    
    drawA(t)
    
    turtle.mainloop()